### ISSUE TITLE
Fiddle::DLError: dlopen(ruby-2.6.6/gems/argon2-kdf-0.1.4/vendor/libargon2.dylib, 9): no suitable image found.

### ISSUE THREAD

**Issue by dalezak** [ankane/argon2-kdf#4]
I'm getting the error `argon2-kdf-0.1.4/vendor/libargon2.dylib, 9): no suitable image found` on new MacBook Pro with M1 chip:

```
Fiddle::DLError: dlopen(/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/vendor/libargon2.dylib, 9): no suitable image found.  Did find:
	/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/vendor/libargon2.dylib: mach-o, but wrong architecture
	/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/vendor/libargon2.dylib: mach-o, but wrong architecture
/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/lib/argon2/kdf/ffi.rb:8:in `<module:FFI>'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/lib/argon2/kdf/ffi.rb:3:in `<module:KDF>'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/lib/argon2/kdf/ffi.rb:2:in `<module:Argon2>'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/lib/argon2/kdf/ffi.rb:1:in `<main>'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/lib/argon2/kdf.rb:49:in `kdf'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/argon2-kdf-0.1.4/lib/argon2/kdf.rb:40:in `argon2id'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/blind_index-2.2.0/lib/blind_index.rb:68:in `generate_bidx'
/Users/dale/.rvm/gems/ruby-2.6.6/gems/blind_index-2.2.0/lib/blind_index/extensions.rb:42:in `build'
```

Is there a known problem with `blind_index` on M1 chips? Or do you think something else is causing this error?

**Comment by dalezak** [comment]
```
Gem::Platform.local
 => #<Gem::Platform:0x000000012d836458 @cpu="", @os="darwin", @version="20" @cpu="", @os="darwin", @version="20">
```
```
Gem::Platform.local.to_s
 => "-darwin-20"
```

**Comment by ankane** [comment]
Thanks @dalezak. It looks like `Gem::Platform.local` uses `arch` internally (and also JRuby doesn't include the cpu type in `arch`), so seems like `host_cpu` is best to use. Just pushed out a new release (0.1.5).

I think the `arch` may cause issues with gems prepackaged for specific platforms (for instance, there's a `arm64-darwin` [release of Nokogiri](https://rubygems.org/gems/nokogiri/versions/1.11.0-arm64-darwin), but my guess is it won't be picked up on your machine). If it's a typical RVM install, it may be worth reporting to RVM.

Edit: You can run `gem install nokogiri` to see if that's the case. Installation should be pretty much instant and it should output `nokogiri-1.11.0-arm64-darwin` if the prepackaged version is used.

**Comment by dalezak** [comment]
Thank you @ankane, the `0.1.5` release worked, you are amazing!! 🤩
